### ISSUE TITLE
'GeoPoint' object does not support indexing

### ISSUE THREAD

**Issue by balzer82** [doersino/aerialbot#5]
When using a point instead of shapefile in config, the while True loop is not stopped by break, because shapefile is None. In the second try, one gets the error

```
Traceback (most recent call last):
  File "aerialbot.py", line 940, in <module>
    main()
  File "aerialbot.py", line 838, in main
    point = GeoPoint(point[0], point[1])
TypeError: 'GeoPoint' object does not support indexing
```

Because point was already converted to GeoPoint in the first run.

**Comment by doersino** [comment]
Thanks for pointing this out! I've just pushed a fix – could you check whether it resolves your issue?
